Improve cross compilation support
When building a project using os_clock on OSX but with a command like `cargo build --target aarch64-unknown-linux-musl`, the build fails with error
```
  ./src/mach/mach_wrapper.h:1:10: fatal error: 'mach/mach_init.h' file not found
```
This is because the target for the build script is the local computer and not the one specified on the command line.
This build script is used to generate bindings for Apple OSs, which we don't need when cross compiling.
Instead, we can check the actual Cargo target.